name: Compilar TWRP Pettyl

on:
  workflow_dispatch:

jobs:
  build:
    # Actualizamos a ubuntu-22.04 ya que GitHub está retirando 20.04
    runs-on: ubuntu-22.04 
    
    steps:
    - name: Limpiar espacio en disco
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: false

    - name: Configurar entorno
      uses: actions/checkout@v4

    - name: Instalar dependencias (Forzando Python 2 de forma segura)
      run: |
        sudo apt-get update
        # Añadí 'rsync' porque a veces ubuntu-22.04 no lo incluye por defecto y la compilación lo pide.
        sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5-dev libssl-dev x11proto-core-dev libx11-dev libgl1-mesa-dev g++-multilib libxml2-utils xsltproc unzip python2 rsync
        
        # GitHub Actions anula las rutas del sistema (/usr/bin/python). 
        # Creamos un enlace de python2 en un directorio personal y lo ponemos de primero en el PATH.
        # De esta forma, 'python' abrirá Python 2 (necesario para Android 8.1), 
        # pero 'python3' seguirá funcionando (necesario para el comando 'repo').
        mkdir -p $HOME/bin
        ln -s /usr/bin/python2 $HOME/bin/python
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Configurar repo y sincronizar TWRP 8.1
      run: |
        sudo curl -sL https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod a+rx /usr/local/bin/repo
        
        mkdir ~/twrp
        cd ~/twrp
        
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1
        repo sync -j$(nproc --all) --force-sync

    - name: Clonar Árbol del Dispositivo (Pettyl)
      run: |
        cd ~/twrp
        git clone https://github.com/mateus1619/android_device_motorola_pettyl device/motorola/pettyl

    - name: Compilar Recovery
      run: |
        cd ~/twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch omni_pettyl-eng
        make recoveryimage -j$(nproc --all)

    - name: Subir Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Pettyl-8.1
        path: ~/twrp/out/target/product/pettyl/recovery.img
