name: Compilar TWRP Pettyl

on:
  workflow_dispatch:

jobs:
  build:
    # VOLVEMOS A 20.04: Es el más estable para Android 8.1 y Python 2
    runs-on: ubuntu-20.04 
    
    steps:
    - name: Limpiar espacio en disco
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: false

    - name: Configurar entorno
      uses: actions/checkout@v4

    - name: Instalar dependencias (Forzando Python 2)
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5-dev libssl-dev x11proto-core-dev libx11-dev libgl1-mesa-dev g++-multilib libxml2-utils xsltproc unzip python2
        # Engañamos al sistema para que 'python' abra 'python2'
        sudo ln -sf /usr/bin/python2 /usr/bin/python

    - name: Configurar repo y sincronizar TWRP 8.1
      run: |
        sudo curl -sL https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod a+rx /usr/local/bin/repo
        
        mkdir ~/twrp
        cd ~/twrp
        
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1
        repo sync -j$(nproc --all) --force-sync

    - name: Clonar Árbol del Dispositivo (Pettyl)
      run: |
        cd ~/twrp
        git clone https://github.com/mateus1619/android_device_motorola_pettyl device/motorola/pettyl

    - name: Compilar Recovery (Aprovechando CPUs en paralelo)
      run: |
        cd ~/twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch omni_pettyl-eng
        make recoveryimage -j$(nproc --all)

    - name: Subir Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Pettyl-8.1
        path: ~/twrp/out/target/product/pettyl/recovery.img
