name: Compilar TWRP Pettyl

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 
    
    steps:
    - name: Limpiar espacio en disco
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: false

    - name: Configurar entorno
      uses: actions/checkout@v4

    # SOLUCIÓN AL ERROR DE COMPILACIÓN: Forzamos el uso de Java 8
    - name: Configurar Java 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        # Añadimos libncurses5 explicitamente para arreglar el error de clang
        sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5 libncurses5-dev libssl-dev x11proto-core-dev libx11-dev libgl1-mesa-dev g++-multilib libxml2-utils xsltproc unzip python2 rsync
        
        # Engañamos al PATH para que 'python' abra Python 2
        mkdir -p $HOME/bin
        ln -s /usr/bin/python2 $HOME/bin/python
        echo "$HOME/bin" >> $GITHUB_PATH
        
    - name: Configurar repo y sincronizar TWRP 8.1
      run: |
        # Añadido -v (verbose) a curl para ver información de depuración
        sudo curl -vL https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod a+rx /usr/local/bin/repo
        
        mkdir ~/twrp
        cd ~/twrp
        
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1
        
        # Añadido --verbose para más detalles de la descarga y forzando todos los núcleos
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --verbose

    - name: Clonar Árbol del Dispositivo (Pettyl)
      run: |
        cd ~/twrp
        git clone https://github.com/mateus1619/android_device_motorola_pettyl device/motorola/pettyl

    - name: Compilar Recovery (Explotando todos los núcleos)
      run: |
        cd ~/twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch omni_pettyl-eng
        # $(nproc --all) garantiza el uso absoluto de todos los núcleos disponibles
        make recoveryimage -j$(nproc --all)

    - name: Subir Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Pettyl-8.1
        path: ~/twrp/out/target/product/pettyl/recovery.img
